DROP TABLE Parrainage;
DROP TABLE Recoit;
DROP TABLE Cohabite;
DROP TABLE Specialite;
DROP TABLE Travaille;
DROP TABLE Repare_enclos;
DROP TABLE Nettoie;
DROP TABLE Contrat ;
DROP TABLE Gain;
DROP TABLE Aliment;
DROP TABLE Remplacement;
DROP TABLE Réparation ;
DROP TABLE Prestataire;
DROP TABLE Soin;
DROP TABLE Nourriture ;
DROP TABLE Personnel ;
DROP TABLE Boutique;
DROP TABLE Animal ;
DROP TABLE Enclos;
DROP TABLE Visiteur;
DROP TABLE Espece ;
DROP TABLE ZONE;
